export const DUCKING_VOLUME = 0.1;
export const PIXELS_PER_SECOND = 30;
export const TICK_INTERVAL = 5;
export const RETURN_URL = "https://vinhng10.github.io";
export const SUPABASE_URL = "http://10.0.0.25:54321";
export const SUPABASE_PUBLISHABLE_KEY =
  "sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH";
export const STRIPE_PUBLISHABLE_KEY =
  "pk_test_51ShVfcKFOPkzrjS9Gtrjm5RwkYpqhlSkWKBXt7BOJlK92UYi0MEloUnb9RaHSRt0FZlb2ookth7QfCxKBNq2bg8V00I08ol1mn";

export enum StyleEnum {
  Bachata = "Bachata",
  Ballet = "Ballet",
  Ballroom = "Ballroom",
  Bollywood = "Bollywood",
  Breaking = "Breaking",
  Broadway = "Broadway",
  Commercial = "Commercial",
  Contemporary = "Contemporary",
  Heels = "Heels",
  HipHop = "Hip Hop",
  House = "House",
  Jazz = "Jazz",
  KPop = "K-Pop",
  Krump = "Krump",
  Popping = "Popping",
  Reggaeton = "Reggaeton",
  Salsa = "Salsa",
  Shuffle = "Shuffle",
  Tutting = "Tutting",
  Waacking = "Waacking",
  Zumba = "Zumba",
}

export enum LevelEnum {
  Beginner = "Beginner",
  Intermediate = "Intermediate",
  Advanced = "Advanced",
  OpenLevel = "Open Level",
}

export enum ProjectStatusEnum {
  Draft = "Draft",
  Release = "Release",
  Cancel = "Cancel",
}

export enum StripePaymentStatusEnum {
  Succeeded = "Succeeded",
  Processing = "Processing",
  Failed = "Failed",
}

export enum WishStatusEnum {
  ClassAvailable = "Class available",
  Granted = "Granted",
  Waiting = "Waiting",
}

export enum RoleEnum {
  Student = "Student",
  Teacher = "Teacher",
}

export enum DayEnum {
  Sunday = "Sunday",
  Monday = "Monday",
  Tuesday = "Tuesday",
  Wednesday = "Wednesday",
  Thursday = "Thursday",
  Friday = "Friday",
  Saturday = "Saturday",
}

export enum MonthEnum {
  January = "January",
  February = "February",
  March = "March",
  April = "April",
  May = "May",
  June = "June",
  July = "July",
  August = "August",
  September = "September",
  October = "October",
  November = "November",
  December = "December",
}

export enum TrackEnum {
  Song = "song",
  Count = "count",
}

export enum TimeEnum {
  Today = "Today",
  Upcoming = "Upcoming",
  Past = "Past",
}

export enum CountryEnum {
  AF = "Afghanistan",
  AL = "Albania",
  DZ = "Algeria",
  AS = "American Samoa",
  AD = "Andorra",
  AO = "Angola",
  AI = "Anguilla",
  AQ = "Antarctica",
  AG = "Antigua and Barbuda",
  AR = "Argentina",
  AM = "Armenia",
  AW = "Aruba",
  AU = "Australia",
  AT = "Austria",
  AZ = "Azerbaijan",
  BS = "Bahamas",
  BH = "Bahrain",
  BD = "Bangladesh",
  BB = "Barbados",
  BY = "Belarus",
  BE = "Belgium",
  BZ = "Belize",
  BJ = "Benin",
  BM = "Bermuda",
  BT = "Bhutan",
  BO = "Bolivia",
  BQ = "Bonaire",
  BA = "Bosnia and Herzegovina",
  BW = "Botswana",
  BV = "Bouvet Island",
  BR = "Brazil",
  IO = "British Indian Ocean Territory",
  BN = "Brunei",
  BG = "Bulgaria",
  BF = "Burkina Faso",
  BI = "Burundi",
  KH = "Cambodia",
  CM = "Cameroon",
  CA = "Canada",
  CV = "Cape Verde",
  KY = "Cayman Islands",
  CF = "Central African Republic",
  TD = "Chad",
  CL = "Chile",
  CN = "China",
  CX = "Christmas Island",
  CC = "Cocos (Keeling) Islands",
  CO = "Colombia",
  KM = "Comoros",
  CG = "Congo",
  CD = "Congo, the Democratic Republic of the",
  CK = "Cook Islands",
  CR = "Costa Rica",
  HR = "Croatia",
  CU = "Cuba",
  CW = "Curaçao",
  CY = "Cyprus",
  CZ = "Czech Republic",
  CI = "Côte d'Ivoire",
  DK = "Denmark",
  DJ = "Djibouti",
  DM = "Dominica",
  DO = "Dominican Republic",
  EC = "Ecuador",
  EG = "Egypt",
  SV = "El Salvador",
  GQ = "Equatorial Guinea",
  ER = "Eritrea",
  EE = "Estonia",
  SZ = "Eswatini",
  ET = "Ethiopia",
  FK = "Falkland Islands",
  FO = "Faroe Islands",
  FJ = "Fiji",
  FI = "Finland",
  FR = "France",
  GA = "Gabon",
  GM = "Gambia",
  GE = "Georgia",
  DE = "Germany",
  GH = "Ghana",
  GI = "Gibraltar",
  GR = "Greece",
  GL = "Greenland",
  GD = "Grenada",
  GP = "Guadeloupe",
  GU = "Guam",
  GT = "Guatemala",
  GG = "Guernsey",
  GN = "Guinea",
  GW = "Guinea-Bissau",
  GY = "Guyana",
  HT = "Haiti",
  VA = "Vatican City",
  HN = "Honduras",
  HK = "Hong Kong",
  HU = "Hungary",
  IS = "Iceland",
  IN = "India",
  ID = "Indonesia",
  IR = "Iran",
  IQ = "Iraq",
  IE = "Ireland",
  IM = "Isle of Man",
  IL = "Israel",
  IT = "Italy",
  JM = "Jamaica",
  JP = "Japan",
  JE = "Jersey",
  JO = "Jordan",
  KZ = "Kazakhstan",
  KE = "Kenya",
  KI = "Kiribati",
  KP = "North Korea",
  KR = "South Korea",
  KW = "Kuwait",
  KG = "Kyrgyzstan",
  LA = "Laos",
  LV = "Latvia",
  LB = "Lebanon",
  LS = "Lesotho",
  LR = "Liberia",
  LY = "Libya",
  LI = "Liechtenstein",
  LT = "Lithuania",
  LU = "Luxembourg",
  MO = "Macao",
  MK = "North Macedonia",
  MG = "Madagascar",
  MW = "Malawi",
  MY = "Malaysia",
  MV = "Maldives",
  ML = "Mali",
  MT = "Malta",
  MH = "Marshall Islands",
  MQ = "Martinique",
  MR = "Mauritania",
  MU = "Mauritius",
  YT = "Mayotte",
  MX = "Mexico",
  FM = "Micronesia",
  MD = "Moldova",
  MC = "Monaco",
  MN = "Mongolia",
  ME = "Montenegro",
  MS = "Montserrat",
  MA = "Morocco",
  MZ = "Mozambique",
  MM = "Myanmar",
  NA = "Namibia",
  NR = "Nauru",
  NP = "Nepal",
  NL = "Netherlands",
  NC = "New Caledonia",
  NZ = "New Zealand",
  NI = "Nicaragua",
  NE = "Niger",
  NG = "Nigeria",
  NU = "Niue",
  NO = "Norway",
  OM = "Oman",
  PK = "Pakistan",
  PA = "Panama",
  PG = "Papua New Guinea",
  PY = "Paraguay",
  PE = "Peru",
  PH = "Philippines",
  PL = "Poland",
  PT = "Portugal",
  PR = "Puerto Rico",
  QA = "Qatar",
  RO = "Romania",
  RU = "Russia",
  RW = "Rwanda",
  SA = "Saudi Arabia",
  SN = "Senegal",
  RS = "Serbia",
  SG = "Singapore",
  SK = "Slovakia",
  SI = "Slovenia",
  ZA = "South Africa",
  ES = "Spain",
  LK = "Sri Lanka",
  SE = "Sweden",
  CH = "Switzerland",
  TW = "Taiwan",
  TH = "Thailand",
  TR = "Turkey",
  UA = "Ukraine",
  AE = "United Arab Emirates",
  GB = "United Kingdom",
  US = "United States",
  UY = "Uruguay",
  UZ = "Uzbekistan",
  VN = "Viet Nam",
  ZM = "Zambia",
  ZW = "Zimbabwe",
  AX = "Åland Islands",
}
