fit:
  seed_everything: 1
  trainer:
    accelerator: auto
    strategy: auto
    devices: auto
    num_nodes: 1
    precision: bf16-mixed
    logger:
      class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: ./lightning_logs
        name: null
        version: kws-1.0.0
        log_graph: false
        default_hp_metric: false
        prefix: ""
        sub_dir: null
    callbacks:
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          dirpath: null
          filename: "{epoch}-{val_f1:.3f}"
          monitor: val_f1
          verbose: false
          save_last: true
          save_top_k: 3
          save_weights_only: false
          mode: max
      - class_path: lightning.pytorch.callbacks.LearningRateMonitor
        init_args:
          logging_interval: step
          log_momentum: false
    fast_dev_run: false
    max_epochs: 5000
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1
    gradient_clip_val: null
    gradient_clip_algorithm: null
    sync_batchnorm: false
    log_every_n_steps: 5
  model:
    model:
      class_path: models.KWS
      init_args:
        layer_config:
          [
            [1, 32, 1, [3, 3], [2, 2]],
            [1, 16, 1, [3, 3], [1, 1]],
            [3, 24, 1, [3, 3], [2, 2]],
            [3, 32, 1, [3, 3], [2, 2]],
            [3, 64, 1, [3, 3], [2, 2]],
          ]
        sample_rate: 24000
        n_fft: 1024
        n_mels: 128
        rms: 0.05
    optimizer:
      class_path: torch.optim.AdamW
      init:
        lr: 1e-3
        betas:
          - 0.9
          - 0.999
        eps: 1.0e-06
        weight_decay: 1e-3
    # lr_scheduler:
    #   class_path: main.ConstantLRwithWarmup
    #   init:
    #     warmup_steps: 100
    #     warmup_lr: 0.0
  data:
    num_workers: 0
    batch_size: 8
    val_batch_size: 8
    prefetch_factor: 2
    train_dataset:
      class_path: data.KWSDataset
      init_args:
        sounds_path: data/train/voice
        sampling_rate: 16000
        transforms:
          class_path: audiomentations.Compose
          init_args:
            transforms:
              - class_path: audiomentations.TimeStretch
                init_args:
                  min_rate: 0.8
                  max_rate: 1.25
                  leave_length_unchanged: false
                  p: 1.0
              - class_path: audiomentations.AdjustDuration
                init_args:
                  duration_samples: 16000
                  p: 1.0
              - class_path: audiomentations.AirAbsorption
                init_args:
                  min_distance: 10.0
                  max_distance: 800.0
                  p: 1.0
              - class_path: audiomentations.LowPassFilter
                init_args:
                  min_cutoff_freq: 1000
                  max_cutoff_freq: 8000
                  p: 0.5
              - class_path: audiomentations.AddBackgroundNoise
                init_args:
                  sounds_path: data/train/noise
                  min_snr_db: -25.0
                  max_snr_db: 0.0
                  noise_transform:
                    class_path: audiomentations.Compose
                    init_args:
                      transforms:
                        - class_path: audiomentations.AirAbsorption
                          init_args:
                            min_distance: 10.0
                            max_distance: 100.0
                            p: 1.0
                        - class_path: audiomentations.LowPassFilter
                          init_args:
                            min_cutoff_freq: 1000
                            max_cutoff_freq: 8000
                            p: 1.0
                  p: 0.7
              - class_path: data.ImpulseResponse
                init_args:
                  sounds_path: data/train/ir
                  p: 0.7
              - class_path: audiomentations.PolarityInversion
                init_args:
                  p: 0.5
              - class_path: data.ToTensor
                init_args:
                  p: 1.0
    val_dataset:
      class_path: data.KWSDataset
      init_args:
        sounds_path: data/val/voice
        sampling_rate: 16000
        transforms:
          class_path: audiomentations.Compose
          init_args:
            transforms:
              - class_path: audiomentations.TimeStretch
                init_args:
                  min_rate: 0.8
                  max_rate: 1.25
                  leave_length_unchanged: false
                  p: 0.0
              - class_path: audiomentations.AdjustDuration
                init_args:
                  duration_samples: 16000
                  p: 1.0
              - class_path: audiomentations.AirAbsorption
                init_args:
                  min_distance: 10.0
                  max_distance: 800.0
                  p: 1.0
              - class_path: audiomentations.LowPassFilter
                init_args:
                  min_cutoff_freq: 1000
                  max_cutoff_freq: 8000
                  p: 0.5
              - class_path: audiomentations.AddBackgroundNoise
                init_args:
                  sounds_path: data/val/noise
                  min_snr_db: -25.0
                  max_snr_db: 0.0
                  noise_transform:
                    class_path: audiomentations.Compose
                    init_args:
                      transforms:
                        - class_path: audiomentations.AirAbsorption
                          init_args:
                            min_distance: 10.0
                            max_distance: 100.0
                            p: 1.0
                        - class_path: audiomentations.LowPassFilter
                          init_args:
                            min_cutoff_freq: 1000
                            max_cutoff_freq: 8000
                            p: 1.0
                  p: 0.7
              - class_path: data.ImpulseResponse
                init_args:
                  sounds_path: data/val/ir
                  p: 0.7
              - class_path: audiomentations.PolarityInversion
                init_args:
                  p: 0.5
              - class_path: data.ToTensor
                init_args:
                  p: 1.0
  # ckpt_path: lightning_logs/flow-1.0.0/checkpoints/last.ckpt
