-- =============================================================================
-- Reports
-- =============================================================================

-- Report status enum
CREATE TYPE "public"."report_status" AS ENUM (
    'Pending',
    'Reviewing',
    'Resolved',
    'Dismissed'
);

ALTER TYPE "public"."report_status" OWNER TO "postgres";

-- Reports table
CREATE TABLE IF NOT EXISTS "public"."reports" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" REFERENCES "auth"."users"("id"),
    "project_id" bigint REFERENCES "public"."projects"("id"),
    "description" "text" NOT NULL,
    "photo_urls" "jsonb",
    "status" "public"."report_status" DEFAULT 'Pending'::"public"."report_status" NOT NULL,
    "resolution" "text"
);

ALTER TABLE "public"."reports" OWNER TO "postgres";

ALTER TABLE "public"."reports" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reports_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."reports" ADD CONSTRAINT "reports_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."reports" ADD CONSTRAINT "reports_user_project_key" UNIQUE ("user_id", "project_id");

CREATE INDEX "reports_project_id_idx" ON "public"."reports" ("project_id");

ALTER TABLE "public"."reports" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read own reports"
ON "public"."reports" FOR SELECT TO "authenticated"
USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

CREATE POLICY "Enable insert own reports"
ON "public"."reports" FOR INSERT TO "authenticated"
WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

-- =============================================================================
-- Update enqueue_transfers to hold bookings with pending reports
-- =============================================================================

CREATE OR REPLACE FUNCTION "public"."enqueue_transfers"() RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
DECLARE
  msgs jsonb[];
BEGIN
  -- Atomically mark eligible bookings and collect their IDs
  -- Skip bookings where the student has a pending report on the project
  WITH flagged AS (
    UPDATE public.bookings b
    SET status = 'Transferred'
    FROM public.projects p
    WHERE p.id = b.project_id
      AND b.status = 'CheckedIn'
      AND p.end_at < now() - interval '48 hours'
      AND NOT EXISTS (
        SELECT 1 FROM public.reports r
        WHERE r.project_id = b.project_id
          AND r.user_id = b.user_id
          AND r.status = 'Pending'::"public"."report_status"
      )
    RETURNING b.id
  )
  SELECT array_agg(jsonb_build_object('id', f.id))
  INTO msgs
  FROM flagged f;

  IF msgs IS NOT NULL THEN
    PERFORM pgmq.send_batch(
      queue_name => 'transfer_jobs',
      msgs => msgs
    );
  END IF;
END;
$$;

-- =============================================================================
-- Storage bucket for report photos
-- =============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('reports', 'reports', false, 10485760, ARRAY['image/*']);

CREATE POLICY "reports_insert"
ON "storage"."objects" AS permissive FOR INSERT TO authenticated
WITH CHECK (((bucket_id = 'reports'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));

CREATE POLICY "reports_select"
ON "storage"."objects" AS permissive FOR SELECT TO authenticated
USING (((bucket_id = 'reports'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));
