create extension if not exists "pg_cron" with schema "pg_catalog";

create extension if not exists "hstore" with schema "extensions";

create extension if not exists "postgis" with schema "extensions";

create extension if not exists "vector" with schema "extensions";

create schema if not exists "pgmq";

create extension if not exists "pgmq" with schema "pgmq";

create schema if not exists "stripe";

create schema if not exists "util";

create type "public"."country_code" as enum ('AF', 'AL', 'DZ', 'AS', 'AD', 'AO', 'AI', 'AQ', 'AG', 'AR', 'AM', 'AW', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BM', 'BT', 'BO', 'BQ', 'BA', 'BW', 'BV', 'BR', 'IO', 'BN', 'BG', 'BF', 'BI', 'KH', 'CM', 'CA', 'CV', 'KY', 'CF', 'TD', 'CL', 'CN', 'CX', 'CC', 'CO', 'KM', 'CG', 'CD', 'CK', 'CR', 'HR', 'CU', 'CW', 'CY', 'CZ', 'CI', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'SZ', 'ET', 'FK', 'FO', 'FJ', 'FI', 'FR', 'GF', 'PF', 'TF', 'GA', 'GM', 'GE', 'DE', 'GH', 'GI', 'GR', 'GL', 'GD', 'GP', 'GU', 'GT', 'GG', 'GN', 'GW', 'GY', 'HT', 'HM', 'VA', 'HN', 'HK', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IM', 'IL', 'IT', 'JM', 'JP', 'JE', 'JO', 'KZ', 'KE', 'KI', 'KP', 'KR', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MO', 'MK', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MQ', 'MR', 'MU', 'YT', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MS', 'MA', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NL', 'NC', 'NZ', 'NI', 'NE', 'NG', 'NU', 'NF', 'MP', 'NO', 'OM', 'PK', 'PW', 'PS', 'PA', 'PG', 'PY', 'PE', 'PH', 'PN', 'PL', 'PT', 'PR', 'QA', 'RO', 'RU', 'RW', 'RE', 'BL', 'SH', 'KN', 'LC', 'MF', 'PM', 'VC', 'WS', 'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'GS', 'SS', 'ES', 'LK', 'SD', 'SR', 'SJ', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TL', 'TG', 'TK', 'TO', 'TT', 'TN', 'TR', 'TM', 'TC', 'TV', 'UG', 'UA', 'AE', 'GB', 'US', 'UM', 'UY', 'UZ', 'VU', 'VE', 'VN', 'VG', 'VI', 'WF', 'EH', 'YE', 'ZM', 'ZW', 'AX');

create type "public"."level" as enum ('Beginner', 'Intermediate', 'Advanced', 'Open Level');

create type "public"."status" as enum ('Draft', 'Release', 'Cancel');

create type "public"."stripe_payment_status" as enum ('Succeeded', 'Processing', 'Failed', 'Canceled', 'Refunded', 'Refunding');

create type "public"."style" as enum ('Bachata', 'Ballet', 'Ballroom', 'Bollywood', 'Breaking', 'Broadway', 'Commercial', 'Contemporary', 'Heels', 'Hip Hop', 'House', 'Jazz', 'K-Pop', 'Krump', 'Popping', 'Reggaeton', 'Salsa', 'Shuffle', 'Tutting', 'Waacking', 'Zumba');


  create table "public"."bookings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "project_id" bigint not null,
    "stripe_payment_intent_id" text not null,
    "status" public.stripe_payment_status,
    "updated_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
    "spots" smallint default '1'::smallint
      );


alter table "public"."bookings" enable row level security;


  create table "public"."centroids" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "genre" text,
    "embedding" extensions.vector(2)
      );


alter table "public"."centroids" enable row level security;


  create table "public"."locations" (
    "id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "display_name" text,
    "formatted_address" text,
    "short_formatted_address" text,
    "google_maps_uri" text,
    "location" extensions.geometry,
    "country" public.country_code,
    "administrative_area_level_1" text
      );


alter table "public"."locations" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
    "username" text,
    "full_name" text,
    "avatar_url" text,
    "bio" text,
    "video_urls" jsonb,
    "stripe_account_id" text,
    "location" extensions.geometry,
    "country" public.country_code default 'US'::public.country_code,
    "expo_push_token" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
    "name" text,
    "status" public.status default 'Draft'::public.status,
    "style" public.style,
    "level" public.level,
    "price" integer,
    "spots" smallint,
    "start_at" timestamp with time zone,
    "end_at" timestamp with time zone,
    "description" text,
    "song_id" text,
    "song_items" jsonb default '[]'::jsonb,
    "count_items" jsonb default '[]'::jsonb,
    "user_id" uuid default auth.uid(),
    "currency" text not null,
    "location_id" text
      );


alter table "public"."projects" enable row level security;


  create table "public"."recommendation_items" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "wish_id" bigint,
    "project_id" bigint,
    "score" double precision
      );


alter table "public"."recommendation_items" enable row level security;


  create table "public"."songs" (
    "id" text not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "name" text,
    "artist_name" text,
    "artwork_url" text,
    "genre" text,
    "preview_url" text,
    "embedding" extensions.vector(2),
    "centroid_id" bigint
      );


alter table "public"."songs" enable row level security;


  create table "public"."watchings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "project_id" bigint
      );


alter table "public"."watchings" enable row level security;


  create table "public"."wishes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "user_id" uuid default auth.uid(),
    "style" public.style,
    "level" public.level,
    "description" text,
    "song_id" text
      );


alter table "public"."wishes" enable row level security;

CREATE UNIQUE INDEX bookings_pkey ON public.bookings USING btree (id);

CREATE UNIQUE INDEX bookings_stripe_payment_intent_id_key ON public.bookings USING btree (stripe_payment_intent_id);

CREATE INDEX centroids_embedding_idx ON public.centroids USING hnsw (embedding extensions.vector_cosine_ops);

CREATE UNIQUE INDEX centroids_pkey ON public.centroids USING btree (id);

CREATE INDEX locations_location_idx ON public.locations USING gist (location);

CREATE UNIQUE INDEX locations_pkey ON public.locations USING btree (id);

CREATE INDEX profiles_location_idx ON public.profiles USING gist (location);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

CREATE UNIQUE INDEX recommendations_pkey ON public.recommendation_items USING btree (id);

CREATE INDEX songs_embedding_idx ON public.songs USING hnsw (embedding extensions.vector_cosine_ops);

CREATE UNIQUE INDEX songs_pkey ON public.songs USING btree (id);

CREATE UNIQUE INDEX watchings_pkey ON public.watchings USING btree (id);

CREATE UNIQUE INDEX wishes_pkey ON public.wishes USING btree (id);

alter table "public"."bookings" add constraint "bookings_pkey" PRIMARY KEY using index "bookings_pkey";

alter table "public"."centroids" add constraint "centroids_pkey" PRIMARY KEY using index "centroids_pkey";

alter table "public"."locations" add constraint "locations_pkey" PRIMARY KEY using index "locations_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."recommendation_items" add constraint "recommendations_pkey" PRIMARY KEY using index "recommendations_pkey";

alter table "public"."songs" add constraint "songs_pkey" PRIMARY KEY using index "songs_pkey";

alter table "public"."watchings" add constraint "watchings_pkey" PRIMARY KEY using index "watchings_pkey";

alter table "public"."wishes" add constraint "wishes_pkey" PRIMARY KEY using index "wishes_pkey";

alter table "public"."bookings" add constraint "bookings_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) not valid;

alter table "public"."bookings" validate constraint "bookings_project_id_fkey";

alter table "public"."bookings" add constraint "bookings_stripe_payment_intent_id_key" UNIQUE using index "bookings_stripe_payment_intent_id_key";

alter table "public"."bookings" add constraint "bookings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."bookings" validate constraint "bookings_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."profiles" add constraint "username_length" CHECK ((char_length(username) >= 3)) not valid;

alter table "public"."profiles" validate constraint "username_length";

alter table "public"."projects" add constraint "projects_currency_check" CHECK (((char_length(currency) = 3) AND (currency = upper(currency)))) not valid;

alter table "public"."projects" validate constraint "projects_currency_check";

alter table "public"."projects" add constraint "projects_location_id_fkey" FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE SET NULL not valid;

alter table "public"."projects" validate constraint "projects_location_id_fkey";

alter table "public"."projects" add constraint "projects_song_id_fkey" FOREIGN KEY (song_id) REFERENCES public.songs(id) ON DELETE SET NULL not valid;

alter table "public"."projects" validate constraint "projects_song_id_fkey";

alter table "public"."projects" add constraint "projects_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."projects" validate constraint "projects_user_id_fkey";

alter table "public"."recommendation_items" add constraint "recommendation_items_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE not valid;

alter table "public"."recommendation_items" validate constraint "recommendation_items_project_id_fkey";

alter table "public"."recommendation_items" add constraint "recommendation_items_wish_id_fkey" FOREIGN KEY (wish_id) REFERENCES public.wishes(id) ON DELETE CASCADE not valid;

alter table "public"."recommendation_items" validate constraint "recommendation_items_wish_id_fkey";

alter table "public"."songs" add constraint "songs_centroid_id_fkey" FOREIGN KEY (centroid_id) REFERENCES public.centroids(id) not valid;

alter table "public"."songs" validate constraint "songs_centroid_id_fkey";

alter table "public"."watchings" add constraint "watchings_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE not valid;

alter table "public"."watchings" validate constraint "watchings_project_id_fkey";

alter table "public"."watchings" add constraint "watchings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."watchings" validate constraint "watchings_user_id_fkey";

alter table "public"."wishes" add constraint "wishes_song_id_fkey" FOREIGN KEY (song_id) REFERENCES public.songs(id) ON DELETE CASCADE not valid;

alter table "public"."wishes" validate constraint "wishes_song_id_fkey";

alter table "public"."wishes" add constraint "wishes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."wishes" validate constraint "wishes_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_project_with_song(p_song_data jsonb, p_project_data jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$declare
  v_project_id bigint;
begin
  -- Insert song if it doesn't exist
  insert into public.songs (
    id,
    name,
    artist_name,
    artwork_url,
    preview_url,
    genre
  )
  values (
    p_song_data->>'id',
    p_song_data->>'name',
    p_song_data->>'artist_name',
    p_song_data->>'artwork_url',
    p_song_data->>'preview_url',
    p_song_data->>'genre'
  )
  on conflict (id) do nothing;
  
  -- Create the project and capture the ID
  insert into public.projects (
    name,
    status,
    style,
    level,
    price,
    spots,
    description,
    start_at,
    end_at,
    location_id,
    song_id,
    currency
  )
  values (
    p_project_data->>'name',
    (p_project_data->>'status')::public.status,
    (p_project_data->>'style')::public.style,
    (p_project_data->>'level')::public.level,
    (p_project_data->>'price')::integer * 100,
    (p_project_data->>'spots')::smallint,
    p_project_data->>'description',
    (p_project_data->>'start_at')::timestamp with time zone,
    (p_project_data->>'end_at')::timestamp with time zone,
    (p_project_data->>'location_id')::text,
    p_song_data->>'id',
    p_project_data->>'currency'
  )
  returning id into v_project_id;
  
  return v_project_id;
end;$function$
;

CREATE OR REPLACE FUNCTION public.create_wish_with_song(p_song_data jsonb, p_wish_data jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$declare
  v_wish_id bigint;
begin
  -- Insert song if it doesn't exist
  insert into public.songs (
    id,
    name,
    artist_name,
    artwork_url,
    preview_url,
    genre
  )
  values (
    p_song_data->>'id',
    p_song_data->>'name',
    p_song_data->>'artist_name',
    p_song_data->>'artwork_url',
    p_song_data->>'preview_url',
    p_song_data->>'genre'
  )
  on conflict (id) do nothing;
  
  -- Create the wish and capture the ID
  insert into public.wishes (
    song_id,
    style,
    level,
    description
  )
  values (
    p_song_data->>'id',
    (p_wish_data->>'style')::public.style,
    (p_wish_data->>'level')::public.level,
    p_wish_data->>'description'
  )
  returning id into v_wish_id;
  
  return v_wish_id;
end;$function$
;

CREATE OR REPLACE FUNCTION public.get_bubbles(p_style public.style DEFAULT NULL::public.style, p_level public.level DEFAULT NULL::public.level)
 RETURNS TABLE(label bigint, value bigint)
 LANGUAGE plpgsql
AS $function$DECLARE
  user_location geometry;
  user_country public.country_code;
BEGIN
  -- 1. Get current user's location/country
  SELECT location, country INTO user_location, user_country
  FROM public.profiles 
  WHERE id = auth.uid();

  RETURN QUERY
  SELECT 
    s.centroid_id as label,
    COUNT(w.id) AS value
  FROM 
    public.wishes w
    INNER JOIN public.songs s ON w.song_id = s.id
    INNER JOIN public.profiles p ON w.user_id = p.id -- Join to get wisher's location
  WHERE 
    s.centroid_id IS NOT NULL
    AND w.created_at >= DATE_TRUNC('month', NOW() - INTERVAL '3 months')
    AND (p_style IS NULL OR w.style = p_style)
    AND (p_level IS NULL OR w.level = p_level)
    AND w.user_id != auth.uid()
    -- 2. Apply Cascading Location Filter
    AND (
      CASE 
        -- Case A: Both have coordinates -> 1 degree radius (~111km)
        WHEN user_location IS NOT NULL AND p.location IS NOT NULL THEN 
          ST_DWithin(p.location, user_location, 1.0)
        
        -- Case B: Fallback to country matching if coordinates are missing
        WHEN user_country IS NOT NULL THEN 
          p.country = user_country
        
        -- Case C: If browsing user has no profile data, show all
        ELSE TRUE 
      END
    )
  GROUP BY 
    s.centroid_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_nearby_classes()
 RETURNS SETOF public.projects
 LANGUAGE plpgsql
AS $function$
DECLARE
  user_location geometry;
  user_country public.country_code;
BEGIN
  -- Fetch current user data
  SELECT location, country INTO user_location, user_country
  FROM public.profiles 
  WHERE id = auth.uid();

  RETURN QUERY
  SELECT p.*
  FROM public.projects p
  LEFT JOIN public.locations l ON p.location_id = l.id
  WHERE 
    CASE 
      -- 1. Spatial: Both must exist
      WHEN user_location IS NOT NULL AND l.location IS NOT NULL THEN 
        ST_DWithin(l.location, user_location, 1.0)
      
      -- 2. Country Fallback: User has country, filter by location's country
      WHEN user_country IS NOT NULL THEN 
        l.country = user_country
      
      -- 3. Total Fallback: User profile is empty or no country set
      ELSE TRUE 
    END
  ORDER BY 
    (user_location IS NOT NULL AND l.location IS NOT NULL) DESC, -- Prioritize spatial matches
    l.location <-> user_location ASC NULLS LAST,
    p.updated_at DESC;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_nearby_wishes()
 RETURNS SETOF public.wishes
 LANGUAGE plpgsql
AS $function$DECLARE
  user_location geometry;
  user_country public.country_code;
BEGIN
  SELECT location, country INTO user_location, user_country
  FROM public.profiles 
  WHERE id = auth.uid();

  RETURN QUERY
  SELECT w.*
  FROM public.wishes w
  JOIN public.profiles p ON w.user_id = p.id
  WHERE 
    CASE 
      -- 1. Spatial: Both user and "wisher" have coordinates
      WHEN user_location IS NOT NULL AND p.location IS NOT NULL THEN 
        ST_DWithin(p.location, user_location, 1.0)
      
      -- 2. Country Fallback: User has country, filter by wisher's country
      WHEN user_country IS NOT NULL THEN 
        p.country = user_country
      
      -- 3. Total Fallback
      ELSE TRUE 
    END
    AND w.created_at >= DATE_TRUNC('month', NOW() - INTERVAL '3 months')
    AND w.user_id != auth.uid()
  ORDER BY 
    (user_location IS NOT NULL AND p.location IS NOT NULL) DESC,
    p.location <-> user_location ASC NULLS LAST,
    w.created_at DESC;
END;$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  
  perform util.invoke_edge_function(
    name => 'connect-account',
    body => jsonb_build_object('userId', new.id, 'email', new.email),
    timeout_milliseconds => 30000
  );
  
  return new;
end;$function$
;

CREATE OR REPLACE FUNCTION public.manage_project_lifecycle()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
    -- Canceled projects are immutable
    IF OLD.status = 'Cancel' THEN
        RAISE EXCEPTION 'A Canceled project cannot be modified.';
    END IF;

    -- Released projects can only change status to Cancel
    IF OLD.status = 'Release' THEN
        IF NEW.status = 'Draft' THEN
            RAISE EXCEPTION 'Cannot move a Released project back to Draft.';
        END IF;
        
        IF NEW::text IS DISTINCT FROM OLD::text AND NEW.status = OLD.status THEN
            RAISE EXCEPTION 'This project is Released. Only the Status can be changed to Cancel.';
        END IF;
    END IF;

    -- Validate required fields before releasing
    IF NEW.status = 'Release' AND OLD.status = 'Draft' THEN
        IF NEW.style IS NULL OR NEW.level IS NULL OR 
           NEW.price IS NULL OR NEW.spots IS NULL OR NEW.start_at IS NULL OR 
           NEW.end_at IS NULL OR NEW.location_id IS NULL THEN
            RAISE EXCEPTION 'Cannot release: Missing required project details.';
        END IF;
    END IF;

    RETURN NEW;
END;$function$
;

CREATE OR REPLACE VIEW "public"."recommendations"
  WITH (security_invoker = true)
  AS  SELECT ri.id,
    ri.created_at,
    ri.wish_id,
    ri.project_id,
    ri.score
   FROM (public.recommendation_items ri
     JOIN public.projects p ON ((ri.project_id = p.id)))
  WHERE ((ri.created_at >= (now() - '3 mons'::interval)) AND (p.status <> 'Cancel'::public.status) AND (p.start_at >= now()));


CREATE OR REPLACE VIEW "public"."stats"
  WITH (security_invoker = true)
  AS  SELECT p.user_id,
    sum(p.price) AS total_earnings,
    count(b.id) AS booking_count,
    p.currency,
    date_trunc('month'::text, now()) AS current_month
   FROM (public.bookings b
     JOIN public.projects p ON ((b.project_id = p.id)))
  WHERE ((b.status = 'Succeeded'::public.stripe_payment_status) AND (b.updated_at >= date_trunc('month'::text, now())))
  GROUP BY p.user_id, p.currency;


CREATE OR REPLACE FUNCTION public.update_objects_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION util.batch_dequeue(queue_name text, job_ids bigint[])
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$begin
  perform pgmq.delete(
    queue_name => queue_name,
    msg_ids => job_ids
  );
  return true;
exception
  when others then
    return false;
end;$function$
;

CREATE OR REPLACE FUNCTION util.clear_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
    clear_column text := TG_ARGV[0];
begin
    NEW := NEW #= hstore(clear_column, NULL);
    return NEW;
end;
$function$
;

CREATE OR REPLACE FUNCTION util.dequeue(queue_name text, job_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$begin
  perform pgmq.delete(
    queue_name => queue_name,
    msg_id => job_id
  );
  
  return true;
exception
  when others then
    return false;
end;$function$
;

CREATE OR REPLACE FUNCTION util.enqueue()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$declare
  queue_name text = TG_ARGV[0];
begin
  perform pgmq.send(
    queue_name => queue_name,
    msg => jsonb_build_object('id', NEW.id)
  );
  return NEW;
end;$function$
;

CREATE OR REPLACE FUNCTION util.find_nearest_centroid(query_embedding extensions.vector)
 RETURNS bigint
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  select id
  from public.centroids
  order by (public.centroids.embedding <=> query_embedding) asc
  limit 1;
$function$
;

CREATE OR REPLACE FUNCTION util.invoke_edge_function(name text, body jsonb, timeout_milliseconds integer DEFAULT ((5 * 60) * 1000))
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  secret_key text;
begin
  -- Retrieve the secret from Vault
  select decrypted_secret into secret_key from vault.decrypted_secrets as vds where vds.name = 'internal_secret_key';

  -- Perform async HTTP request to the edge function
  perform net.http_post(
    url => util.project_url() || '/functions/v1/' || name,
    headers => jsonb_build_object(
      'Content-Type', 'application/json',
      'X-Internal-Secret-Key', secret_key
    ),
    body => body,
    timeout_milliseconds => timeout_milliseconds
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION util.process_jobs(queue_name text, edge_function_name text, batch_size integer DEFAULT 10, max_requests integer DEFAULT 10, timeout_milliseconds integer DEFAULT ((60) * 1000))
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$declare
  job_batches jsonb[];
  batch jsonb;
begin
  with
    -- Use the dynamic _queue_name in the pgmq.read call
    numbered_jobs as (
      select
        message || jsonb_build_object('jobId', msg_id) as job_info,
        (row_number() over (order by 1) - 1) / batch_size as batch_num
      from pgmq.read(
        queue_name => queue_name,
        vt => timeout_milliseconds / 1000,
        qty => max_requests * batch_size
      )
    ),
    -- Group jobs into batches
    batched_jobs as (
      select
        jsonb_agg(job_info) as batch_array,
        batch_num
      from numbered_jobs
      group by batch_num
    )
  -- Aggregate all batches into array
  select array_agg(batch_array)
  from batched_jobs
  into job_batches;

  -- Exit if no jobs were found to process
  if job_batches is null then
    return;
  end if;

  -- Invoke the specified edge function for each batch
  foreach batch in array job_batches loop
    perform util.invoke_edge_function(
      name => edge_function_name,
      body => batch,
      timeout_milliseconds => timeout_milliseconds
    );
  end loop;
end;$function$
;

CREATE OR REPLACE FUNCTION util.project_url()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  secret_value text;
begin
  -- Retrieve the project URL from Vault
  select decrypted_secret into secret_value from vault.decrypted_secrets where name = 'project_url';
  return secret_value;
end;
$function$
;

grant delete on table "public"."bookings" to "anon";

grant insert on table "public"."bookings" to "anon";

grant references on table "public"."bookings" to "anon";

grant select on table "public"."bookings" to "anon";

grant trigger on table "public"."bookings" to "anon";

grant truncate on table "public"."bookings" to "anon";

grant update on table "public"."bookings" to "anon";

grant delete on table "public"."bookings" to "authenticated";

grant insert on table "public"."bookings" to "authenticated";

grant references on table "public"."bookings" to "authenticated";

grant select on table "public"."bookings" to "authenticated";

grant trigger on table "public"."bookings" to "authenticated";

grant truncate on table "public"."bookings" to "authenticated";

grant update on table "public"."bookings" to "authenticated";

grant delete on table "public"."bookings" to "postgres";

grant insert on table "public"."bookings" to "postgres";

grant references on table "public"."bookings" to "postgres";

grant select on table "public"."bookings" to "postgres";

grant trigger on table "public"."bookings" to "postgres";

grant truncate on table "public"."bookings" to "postgres";

grant update on table "public"."bookings" to "postgres";

grant delete on table "public"."bookings" to "service_role";

grant insert on table "public"."bookings" to "service_role";

grant references on table "public"."bookings" to "service_role";

grant select on table "public"."bookings" to "service_role";

grant trigger on table "public"."bookings" to "service_role";

grant truncate on table "public"."bookings" to "service_role";

grant update on table "public"."bookings" to "service_role";

grant delete on table "public"."centroids" to "anon";

grant insert on table "public"."centroids" to "anon";

grant references on table "public"."centroids" to "anon";

grant select on table "public"."centroids" to "anon";

grant trigger on table "public"."centroids" to "anon";

grant truncate on table "public"."centroids" to "anon";

grant update on table "public"."centroids" to "anon";

grant delete on table "public"."centroids" to "authenticated";

grant insert on table "public"."centroids" to "authenticated";

grant references on table "public"."centroids" to "authenticated";

grant select on table "public"."centroids" to "authenticated";

grant trigger on table "public"."centroids" to "authenticated";

grant truncate on table "public"."centroids" to "authenticated";

grant update on table "public"."centroids" to "authenticated";

grant delete on table "public"."centroids" to "postgres";

grant insert on table "public"."centroids" to "postgres";

grant references on table "public"."centroids" to "postgres";

grant select on table "public"."centroids" to "postgres";

grant trigger on table "public"."centroids" to "postgres";

grant truncate on table "public"."centroids" to "postgres";

grant update on table "public"."centroids" to "postgres";

grant delete on table "public"."centroids" to "service_role";

grant insert on table "public"."centroids" to "service_role";

grant references on table "public"."centroids" to "service_role";

grant select on table "public"."centroids" to "service_role";

grant trigger on table "public"."centroids" to "service_role";

grant truncate on table "public"."centroids" to "service_role";

grant update on table "public"."centroids" to "service_role";

grant delete on table "public"."locations" to "anon";

grant insert on table "public"."locations" to "anon";

grant references on table "public"."locations" to "anon";

grant select on table "public"."locations" to "anon";

grant trigger on table "public"."locations" to "anon";

grant truncate on table "public"."locations" to "anon";

grant update on table "public"."locations" to "anon";

grant delete on table "public"."locations" to "authenticated";

grant insert on table "public"."locations" to "authenticated";

grant references on table "public"."locations" to "authenticated";

grant select on table "public"."locations" to "authenticated";

grant trigger on table "public"."locations" to "authenticated";

grant truncate on table "public"."locations" to "authenticated";

grant update on table "public"."locations" to "authenticated";

grant delete on table "public"."locations" to "postgres";

grant insert on table "public"."locations" to "postgres";

grant references on table "public"."locations" to "postgres";

grant select on table "public"."locations" to "postgres";

grant trigger on table "public"."locations" to "postgres";

grant truncate on table "public"."locations" to "postgres";

grant update on table "public"."locations" to "postgres";

grant delete on table "public"."locations" to "service_role";

grant insert on table "public"."locations" to "service_role";

grant references on table "public"."locations" to "service_role";

grant select on table "public"."locations" to "service_role";

grant trigger on table "public"."locations" to "service_role";

grant truncate on table "public"."locations" to "service_role";

grant update on table "public"."locations" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "postgres";

grant insert on table "public"."projects" to "postgres";

grant references on table "public"."projects" to "postgres";

grant select on table "public"."projects" to "postgres";

grant trigger on table "public"."projects" to "postgres";

grant truncate on table "public"."projects" to "postgres";

grant update on table "public"."projects" to "postgres";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";

grant delete on table "public"."recommendation_items" to "anon";

grant insert on table "public"."recommendation_items" to "anon";

grant references on table "public"."recommendation_items" to "anon";

grant select on table "public"."recommendation_items" to "anon";

grant trigger on table "public"."recommendation_items" to "anon";

grant truncate on table "public"."recommendation_items" to "anon";

grant update on table "public"."recommendation_items" to "anon";

grant delete on table "public"."recommendation_items" to "authenticated";

grant insert on table "public"."recommendation_items" to "authenticated";

grant references on table "public"."recommendation_items" to "authenticated";

grant select on table "public"."recommendation_items" to "authenticated";

grant trigger on table "public"."recommendation_items" to "authenticated";

grant truncate on table "public"."recommendation_items" to "authenticated";

grant update on table "public"."recommendation_items" to "authenticated";

grant delete on table "public"."recommendation_items" to "postgres";

grant insert on table "public"."recommendation_items" to "postgres";

grant references on table "public"."recommendation_items" to "postgres";

grant select on table "public"."recommendation_items" to "postgres";

grant trigger on table "public"."recommendation_items" to "postgres";

grant truncate on table "public"."recommendation_items" to "postgres";

grant update on table "public"."recommendation_items" to "postgres";

grant delete on table "public"."recommendation_items" to "service_role";

grant insert on table "public"."recommendation_items" to "service_role";

grant references on table "public"."recommendation_items" to "service_role";

grant select on table "public"."recommendation_items" to "service_role";

grant trigger on table "public"."recommendation_items" to "service_role";

grant truncate on table "public"."recommendation_items" to "service_role";

grant update on table "public"."recommendation_items" to "service_role";

grant delete on table "public"."songs" to "anon";

grant insert on table "public"."songs" to "anon";

grant references on table "public"."songs" to "anon";

grant select on table "public"."songs" to "anon";

grant trigger on table "public"."songs" to "anon";

grant truncate on table "public"."songs" to "anon";

grant update on table "public"."songs" to "anon";

grant delete on table "public"."songs" to "authenticated";

grant insert on table "public"."songs" to "authenticated";

grant references on table "public"."songs" to "authenticated";

grant select on table "public"."songs" to "authenticated";

grant trigger on table "public"."songs" to "authenticated";

grant truncate on table "public"."songs" to "authenticated";

grant update on table "public"."songs" to "authenticated";

grant delete on table "public"."songs" to "postgres";

grant insert on table "public"."songs" to "postgres";

grant references on table "public"."songs" to "postgres";

grant select on table "public"."songs" to "postgres";

grant trigger on table "public"."songs" to "postgres";

grant truncate on table "public"."songs" to "postgres";

grant update on table "public"."songs" to "postgres";

grant delete on table "public"."songs" to "service_role";

grant insert on table "public"."songs" to "service_role";

grant references on table "public"."songs" to "service_role";

grant select on table "public"."songs" to "service_role";

grant trigger on table "public"."songs" to "service_role";

grant truncate on table "public"."songs" to "service_role";

grant update on table "public"."songs" to "service_role";

grant delete on table "public"."watchings" to "anon";

grant insert on table "public"."watchings" to "anon";

grant references on table "public"."watchings" to "anon";

grant select on table "public"."watchings" to "anon";

grant trigger on table "public"."watchings" to "anon";

grant truncate on table "public"."watchings" to "anon";

grant update on table "public"."watchings" to "anon";

grant delete on table "public"."watchings" to "authenticated";

grant insert on table "public"."watchings" to "authenticated";

grant references on table "public"."watchings" to "authenticated";

grant select on table "public"."watchings" to "authenticated";

grant trigger on table "public"."watchings" to "authenticated";

grant truncate on table "public"."watchings" to "authenticated";

grant update on table "public"."watchings" to "authenticated";

grant delete on table "public"."watchings" to "postgres";

grant insert on table "public"."watchings" to "postgres";

grant references on table "public"."watchings" to "postgres";

grant select on table "public"."watchings" to "postgres";

grant trigger on table "public"."watchings" to "postgres";

grant truncate on table "public"."watchings" to "postgres";

grant update on table "public"."watchings" to "postgres";

grant delete on table "public"."watchings" to "service_role";

grant insert on table "public"."watchings" to "service_role";

grant references on table "public"."watchings" to "service_role";

grant select on table "public"."watchings" to "service_role";

grant trigger on table "public"."watchings" to "service_role";

grant truncate on table "public"."watchings" to "service_role";

grant update on table "public"."watchings" to "service_role";

grant delete on table "public"."wishes" to "anon";

grant insert on table "public"."wishes" to "anon";

grant references on table "public"."wishes" to "anon";

grant select on table "public"."wishes" to "anon";

grant trigger on table "public"."wishes" to "anon";

grant truncate on table "public"."wishes" to "anon";

grant update on table "public"."wishes" to "anon";

grant delete on table "public"."wishes" to "authenticated";

grant insert on table "public"."wishes" to "authenticated";

grant references on table "public"."wishes" to "authenticated";

grant select on table "public"."wishes" to "authenticated";

grant trigger on table "public"."wishes" to "authenticated";

grant truncate on table "public"."wishes" to "authenticated";

grant update on table "public"."wishes" to "authenticated";

grant delete on table "public"."wishes" to "postgres";

grant insert on table "public"."wishes" to "postgres";

grant references on table "public"."wishes" to "postgres";

grant select on table "public"."wishes" to "postgres";

grant trigger on table "public"."wishes" to "postgres";

grant truncate on table "public"."wishes" to "postgres";

grant update on table "public"."wishes" to "postgres";

grant delete on table "public"."wishes" to "service_role";

grant insert on table "public"."wishes" to "service_role";

grant references on table "public"."wishes" to "service_role";

grant select on table "public"."wishes" to "service_role";

grant trigger on table "public"."wishes" to "service_role";

grant truncate on table "public"."wishes" to "service_role";

grant update on table "public"."wishes" to "service_role";


  create policy "Enable read access for all users"
  on "public"."bookings"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable users to update their own data only"
  on "public"."bookings"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id))
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."centroids"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."locations"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."locations"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable users to update their own data only"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = id))
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can insert their own profile"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable insert for users based on user_id"
  on "public"."projects"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."projects"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable users to update their own data only"
  on "public"."projects"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id))
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."recommendation_items"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.wishes
  WHERE ((wishes.id = recommendation_items.wish_id) AND (wishes.user_id = auth.uid())))));



  create policy "Enable insert for authenticated users only"
  on "public"."songs"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."songs"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable delete for users based on user_id"
  on "public"."watchings"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."watchings"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."watchings"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable insert for users based on user_id"
  on "public"."wishes"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."wishes"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER set_booking_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.update_objects_updated_at();

CREATE TRIGGER set_profile_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_objects_updated_at();

CREATE TRIGGER manage_project_lifecycle BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION public.manage_project_lifecycle();
ALTER TABLE "public"."projects" DISABLE TRIGGER "manage_project_lifecycle";

CREATE TRIGGER set_project_updated_at BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION public.update_objects_updated_at();

CREATE TRIGGER notify_on_recommendations AFTER INSERT ON public.recommendation_items FOR EACH ROW EXECUTE FUNCTION util.enqueue('notification_jobs');

CREATE TRIGGER embed_songs_on_insert AFTER INSERT ON public.songs FOR EACH ROW EXECUTE FUNCTION util.enqueue('embedding_jobs');

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Give authenticated users full access to own folder 1ige2ga_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'profiles'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give authenticated users full access to own folder 1ige2ga_1"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'profiles'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give authenticated users full access to own folder 1ige2ga_2"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'profiles'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give authenticated users read access to everything 1ige2ga_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'profiles'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Give authenticated users read and write access 1f8c4ta_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'locations'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Give users authenticated access to folder 1ffg0oo_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'medias'::text) AND (auth.role() = 'authenticated'::text)));



